---
title: "02_tableaux_descriptives"
author: "Marie Plessz"
date: "05/11/2020"
output: github_document
---

```{r setup, include=FALSE}
library(haven)
library(tidyverse)
library(knitr)
library(labelled)
library(gtsummary)
library(gt)

# dossier de référence est toujours le dossier racine
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file() )

#options pour les nombres
options(OutDec= ","  ,
				encoding = "utf-8",
				digits = 1)  

# espace après les milliers
knitr::knit_hooks$set(inline = function(x) {   if(!is.numeric(x)){     x   }else{    prettyNum(round(x,2), big.mark=",")    } }) 

# options générales pour le package gtsummary
 set_gtsummary_theme(theme_gtsummary_compact()) 
theme_gtsummary_language(  language =  "fr")


```


# préparer les données
```{r data}
data_orig <- read_dta("Data/Cree/HDR6_01_tous.dta")

df <- data_orig %>% 
	filter(emploi == 1 | emploi ==2) %>% 
	mutate_if(is.numeric, as_factor) %>% 
	select(-age, -revuc_cho) %>% 
	mutate(emploi = fct_recode(emploi, "Chômage" = "Demandeur d'emploi sans emploi")) %>% 
	mutate(cc = case_when(nmiss == 0 ~ "Complet",
												TRUE ~"Incomplet")) %>% 
	mutate_if(is.factor, fct_drop) # se débarrasser des levels vides

# variables binaires converties en type "logique"
df <- df %>%  
	mutate(avecenf01 = avecenf01 == "EnfantOUI" ) %>% 
	mutate(diffinnow = diffinnow == "DiffFinMoisOUI") %>% 
	mutate(homme = homme == "Homme") %>% 
	mutate(astopsante = astopsante == "AStopSantéOUI") %>% 
	mutate(rorigreschom = rorigreschom == "AllocChoOUI") %>% 
	mutate(rorigresproch = rorigresproch == "ArgentFamOUI") %>% 
	
# labels des modalités
	mutate(conjemploi = fct_recode(conjemploi,
	  "Conjoint en emploi" = "Cjt en emploi"  ,
		"Conjoint Sans emploi" = "Cjt Sans emploi"
	)) %>% 
	mutate( entrain = fct_recode(entrain,
		"Jamais" = "JMSPasEntrain",
		"Parfois" = "PFSPasEntrain",
		"Souvent" = "SVTPasEntrain")) %>% 
	mutate(revuc_mi = fct_recode(revuc_mi,
						"<700 euros"	= "RevUC_-700E",
					"700-1200 euros" =	"RevUC_700-1200E",
					"1200-1800 euros" = "RevUC_1200-1800E",
					 ">1800 euros" =  "RevUC_1800+E"  ) )


# labels
var_label(df) <- list(homme = "Homme", 
								 aveccouple01 = "Vit en couple",
								 avecenf01 = "Vit avec enfant(s)",
								 diffinnow = "Difficultés financières",
								 conjemploi = "Conjoint.e",
								 cp_jmstrav = "Jamais travaillé >6mois",
								 revuc_mi = "Revenu mensuel/UC",
								 age_cl = "Tranche d'âge",
								 tuu2012_cl = "Taille unité urbaine",
								 cc = "Cas complet",
								 diplome3 = "Diplôme", 
								 rorigreschom = "Perçoit allocation chômage"
								 )


```

# tableau 1 
J'utilise le package `gtsummary`.

```{r table, message=FALSE, warning=FALSE, echo= FALSE, result = asis}

t1 <- df %>% select(homme, age_cl, 	conjemploi, avecenf01, 
						 diplome3, astopsante,  cspvol,
						 diffinnow, revuc_mi,  rorigreschom, entrain, emploi) %>% 
		tbl_summary(
			by = emploi,
			missing_text = "N manquantes",
			statistic = all_categorical() ~ "{p}%", # spécifie les stats
			digits = all_categorical() ~ 1  # nb de décimales
			) 

t2 <- df  %>%   filter(emploi =="Chômage") %>%  
	select(homme, age_cl, 	conjemploi, avecenf01, 
							  diplome3, astopsante, cspvol,
							  diffinnow, revuc_mi,  rorigreschom, entrain, cc) %>% 
		tbl_summary(
			by = cc,
			missing_text = "N manquantes",
			statistic = all_categorical() ~ "{p}%",
			digits = all_categorical() ~ 1
			) %>% 
	add_p() # ajoute un test chi2

# réunit les 2 tables en 1
 tmerge<- tbl_merge(
    tbls = list(t1, t2),
    tab_spanner = c("**Ensemble**", "**Parmi les chômeurs**")
  ) %>% 
  bold_labels() %>% 
 	modify_footnote(update = everything() ~ NA)

 tmerge%>% 
 		as_gt() %>% 
    gt::tab_source_note(gt::md(
    	"Source: Constances, extraction du 24/07/2020, données d'inclusion.")) %>% 
  	gtsave(filename = "02_tableau_1.html")
  # le htmal peut être collé dans Word.
  #pour l'instant impossible de spécifier un chemin dans gtsave.
  #je contourne : 
  
 file.copy("02_tableau_1.html", "Resultats", overwrite = TRUE)
 file.remove("02_tableau_1.html")
 

``` 
