---
title: "04_cluster_tableaux"
author: "Marie Plessz"
date: "10/11/2020"
output: word_document
---

Tableaux et illustration pour la classification sur les chômeurs. 

Utilise les résultats de fichier `0x_ACM-cluster.R`.


```{r setup, echo = FALSE}
tag <- "04_cluster_tableaux"

library(tidyverse)
library(knitr)
library(labelled)
library(questionr)
library(glue)
library(haven)

# dossier de référence est toujours le dossier racine
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file() )

#options pour les nombres
options(OutDec= ",")
			#	encoding = "utf-8",
			#	digits = 1
		
# espace après les milliers
knitr::knit_hooks$set(inline = function(x) {if(!is.numeric(x)){ x }else{    prettyNum(round(x,2), big.mark=" ")    } }) 

#charger les données
res.hcpc <- readRDS( file = "Data/res.hcpc.RDS")

```

## taille des clusters

```{r freq}
freq(res.hcpc$data.clust$clust) %>% kable( row.names = T, caption = "Fréquence des classes")

```

## préparation des données


## Description des clusters

```{r desc, results = "asis"}

# préparer les infos pour les effectifs
fr <- freq(res.hcpc$data.clust$clust) 
l_n <- as.list(fr$n)
l_fr <- as.list(fr$`%`)
l_num <- names(res.hcpc$desc.var$category)
caption = glue("Classe {l_num} (n= {l_n} soit {l_fr} %)")	

clean_modalites <- c("Cjt" = "Conjoint", 
	"OUI" = " : oui",
	"NON" = " : non",
	"cspvol =" = "CSP :",
	"TailleUrb" = "Taille unité urbaine :",
	"DejaTrav" = "Déjà eu emploi > 6 mois : oui",
	"JmsTrav" = "Déjà eu emploi >6 mois : non",
		"AllocCho" = "Reçoit alloc. chômage",
	"AStopSanté" = "Déjà eu arrêt travail >6 mois pour raison de santé",
	"ArgentFam" = "Reçoit argent de famille/proches",
	"RevUC_" = "Revenu mensuel par UC :",
	"Employe" = "Employée",
	"DiffFinMois" = "Difficultés financières en fin de mois",
	"-700E" = " <700 euros",
	"0E" = "0 euros",
	"_" = " ",
	"PFSPasEntrain" = "Pas d'entrain : parfois",
	"0k" = "0 000 hab.",
	"2millions" = "2 millions"
	)

for (i in seq_along(res.hcpc$desc.var$category))	{
	res.hcpc$desc.var$category[[i]] %>% 
	as_tibble( rownames = "Modalites") %>% 	
	select( -p.value, - Global ) %>% 	
	slice(1:12) %>% 
	mutate(Modalites = str_replace_all(Modalites, clean_modalites)) %>% 
	mutate(r = str_locate(Modalites, "=")[,1]) %>% 
	mutate(Modalites = str_sub(Modalites, r+1, -1)) %>% 
	select(-r)	%>% 
	mutate_if(is.numeric, ~round(., 3)) %>% 
	kable( caption = caption[i], digits = 1) %>%
  print()
}

```

```{r}

library(questionr)

d1 <- read.csv2("Data/Cree/HDR6-3-coord-cluster.csv") %>%  as_tibble()
d2 <- read_dta("Data/Cree/HDR6_02_chomeurs.dta") %>% 
	as_tibble() %>%  
		mutate(cc = case_when(nmiss == 0 ~ "Complet",
																		 TRUE ~"Incomplet")) %>% 
	mutate_if(is.numeric, as_factor) %>% 
	mutate_if(is.factor, fct_drop) %>% 
	select(proj_isp, cc)

df <- inner_join(d1, d2, by = "proj_isp")

 table(df$clust, df$cc) %>% lprop() %>% 
 	kable( digits = 1, caption = "Pourcentage de cas complets dans chaque classe") 

```

