---
title: "9-modeles-resultatppal"
author: "Marie Plessz"
date: "17/12/2020"
output: html_document
---

m1.coef <- data.frame(coef(summary(m1)))
m1.coef$pval = round((pnorm(abs(m1.coef$t.value), lower.tail = FALSE) * 2),2)

```{r setup, echo = FALSE, warning=FALSE, message=FALSE}

library(tidyverse)
library(knitr)
library(labelled)
library(questionr)
library(glue)
library(broom)
library(modelsummary)
library(kableExtra)
library(GGally)
library(MASS)

select <- dplyr::select # parce que MASS a aussi une fonction select qui entre en conflit avec dplyr

#options pour les nombres
options(OutDec= ",",
				scipen = 999)  

# espace après les milliers
knitr::knit_hooks$set(inline = function(x) {   if(!is.numeric(x)){     x   }else{    prettyNum(round(x,2), big.mark=" ")    } }) 

tag <- "9-modeles-resultatppal"
```

```{r data}
data_orig <- readRDS("Data/Cree/08-appariements-modeles-PASenfant_PAStuu-models.RDS")

data_ordered <- readRDS("Data/Cree/08-appariements-modeles-orderedlogit-PASenfant_PAStuu-models.RDS")

```

```{r fonctions}
f_mod_coefint<- function(mod) {
	broom::tidy(mod, p.value = TRUE, conf.int = TRUE, exponentiate = TRUE) %>% 
		filter( str_detect(term, "traitt")) %>% 
		dplyr::select(estimate, conf.low, conf.high, p.value)
}


f_mod_coeford<- function(mod) {
	# broom::tidy(mod, exponentiate = TRUE) # %>% 
	 data.frame(coef(summary(mod))) %>% 
	 		rownames_to_column(var = "term") %>% 
		filter( str_detect(term, "traitt")) %>% 
	 		mutate(p.value = pnorm(abs(t.value), lower.tail = FALSE) * 2) %>% 
		 mutate(p.value = round(p.value, 7),
		 			 estimate = exp(Value)) %>% 
		mutate(conf.low = exp(Value-1.96*Std..Error),
					 conf.high =  exp(Value+1.96*Std..Error)) %>% 
		select(term, estimate, p.value, conf.low, conf.high)
}


titres <- tribble( ~vardep, ~title,
	"leg_o" , "Légumes: gradient",
	"poi_o" , "Poisson: gradient",
	"vro_o" , "Viande rouge: gradient",
	"fas_o" , "Fast-food: gradient" ,
	"sod_o" , "Sodas: gradient",
	"alc_o" , "Alcool: gradient",
	"fum_o" , "Cigarette : gradient",
	"san_o" , "Santé : gradient",
	"bmi_o" , "Corpulence : gradient"
) %>% 
	rowid_to_column( "ordre")

```
```{r, warning = FALSE}
	mnest <- data_ordered %>%  
#	filter(vardep == "fum_o") %>% 
	select(vardep, model_cem)	%>% 	
	mutate(coefs = map(model_cem, f_mod_coeford))


```



```{r, df_intensite}


df_gradient <- mnest %>% 
		select(vardep, coefs)			 %>% 
	# ajouter les titres
 	left_join(titres, by = "vardep") %>% 
	# transformer les variables "modèles" en liste nommée
	unnest(coefs)  %>% 
	arrange(ordre) %>% 
	mutate(couleur = case_when(	
											(p.value<0.05 & p.value>=0.01 ) ~ "p<0,05",
											p.value<0.01 ~ "p<0,01",
											TRUE ~"p>0.05 (non significatif)")) %>% 
	mutate(term = factor(title),
				 term = fct_reorder(term, ordre))
```


```{r graph_intensite, fig.width = 6, fig.height=5}
footnote <-  glue("Modèle avec appariement (CEM). Programme : {tag}.Rmd")

df_gradient %>% 		
	ggcoef(mapping = aes(x = estimate, 
											 y = reorder(term, -ordre),
				 				 color = couleur),
				 exponentiate = TRUE) +
	theme_bw() +
	theme(legend.position = "bottom",
				 legend.justification='left',
				plot.caption = element_text(vjust = 0,  size = 8)) +
	scale_color_grey(guide_legend(title="Valeur test")) +
#	guides(couleur=guide_legend(title="Significativité")) +
	ylab("Variable dépendante") +
	xlab("Chômage en 2017: odds-ratio") +
		labs(caption = element_text(str_wrap(footnote, 80),
																vjust = 0,  size = 8))

ggsave(file = glue("Resultats/{tag}-graph.png"),width = 6, height=6)
```


